const translations = {
  en: {
    "nav.beaches":"Beaches","nav.food":"Food","nav.experiences":"Experiences","nav.help":"Need help?",
    "hero.eyebrow":"A HANDPICKED ZAKYNTHOS GUIDE","hero.title":"Zakynthos,<br><em>our way.</em>","hero.text":"Places we love, experiences worth having and a few useful tips to help you make the most of your stay.","hero.button":"Start exploring",
    "intro.eyebrow":"THE LOCAL EDIT","intro.title":"Not a list of everything.<br>Just places we genuinely recommend.","intro.text":"Choose the kind of day you want, check the practical notes, and contact the person who shared this guide with you if you need help arranging selected services.",
    "beaches.eyebrow":"BEACH EDIT","beaches.title":"What kind of beach day are you looking for?","beaches.filter.all":"All picks","beaches.filter.favourite":"Our favourites","beaches.filter.easy":"Easy-going","beaches.filter.scenic":"Best water & scenery","beaches.filter.snorkel":"Swim & snorkel","beaches.filter.wild":"Wild & worth the effort",
    "common.goodToKnow":"Good to know","common.map":"View on map ↗",
    "beach.limnionas.label":"Our favourite","beach.limnionas.text":"If we had to choose just one swimming spot in Zakynthos, this would be our pick. Deep blue water, dramatic rock and excellent swimming.","beach.limnionas.note":"Access involves steps and uneven, steep sections. Not recommended for guests with limited mobility or anyone who finds difficult descents uncomfortable.",
    "beach.pelagaki.label":"Hidden favourite","beach.pelagaki.text":"A small, beautiful spot with clear turquoise water and a more secluded feel.","beach.pelagaki.note":"Reaching the beach involves a significant number of steps. Keep this in mind for older guests or anyone looking for easy access.",
    "beach.xigia.label":"Natural beauty","beach.xigia.text":"Small coves, striking water colour and a distinctive natural setting.",
    "beach.roxa.label":"Rocky cove","beach.roxa.text":"A rugged west-coast swimming spot for deep water and rocky scenery.",
    "beach.banana.label":"Easy-going","beach.banana.text":"A long, organised beach for an easy day with facilities.",
    "beach.gerakas.label":"Protected coast","beach.gerakas.text":"A beautiful sandy beach on the Vasilikos peninsula and part of the protected turtle nesting area.",
    "beach.makris.label":"North coast","beach.makris.text":"Clear water and a rocky seabed make this a strong swimming and snorkelling choice.",
    "beach.schoinari.label":"Northern escape","beach.schoinari.text":"For dramatic northern scenery, deep blue water and a more rugged side of Zakynthos close to the Blue Caves.","beach.schoinari.note":"This is better suited to confident swimmers and guests comfortable with rocky swimming spots. It is not a classic sandy beach day.",
    "beach.climati.label":"Quiet favourite","beach.climati.text":"A small pebble cove with exceptionally clear water and a quieter feel. A lovely choice for swimming and snorkelling away from the larger organised beaches.","beach.climati.note":"There are no typical beach facilities or rows of sunbeds. Come prepared for a simple, natural beach stop.",
    "beach.plakaki.label":"Worth the effort","beach.plakaki.text":"Spectacular west-coast rock formations and intensely blue water. This is one of our picks for guests looking for something wild and less conventional.","beach.plakaki.note":"The descent is steep and rocky and requires proper footwear and care. We do not recommend it for older guests, limited mobility or anyone uncomfortable with difficult access.",
    "beach.korakonisi.label":"Natural wonder","beach.korakonisi.text":"A striking rocky inlet and natural swimming spot for guests who want to see one of the island's more dramatic coastal landscapes.","beach.korakonisi.note":"This is an adventurous swimming spot, not a conventional beach. The route down is rocky and steep, shade is limited and access is not suitable for everyone.",
    "beach.kalamaki.label":"Easy sandy choice","beach.kalamaki.text":"A long, sandy and relaxed beach for guests looking for an easier beach day without a difficult descent.","beach.kalamaki.note":"Kalamaki is part of the protected sea turtle nesting area. Please respect marked nests, local guidance and any access restrictions in place.",
    "food.eyebrow":"FOOD & DRINKS","food.title":"Choose by mood, not by ranking.","food.filter.all":"All places","food.filter.special":"A little more special","food.filter.greek":"Taste real Greek food","food.filter.souvlaki":"Traditional souvlaki","food.filter.quick":"Quick & easy","food.filter.sunset":"Drinks & sunset","food.filter.wine":"Wine & local","food.filter.deli":"Deli & local shopping",
    "restaurant.carissimo":"A family-run favourite for Greek and Mediterranean food, preserving local recipes in a friendly, relaxed setting. A particularly useful recommendation for guests looking for gluten-free choices too.","restaurant.nima":"A seafood-focused choice for a more considered dinner.","restaurant.bassia":"Mediterranean dining with a strong focus on fish and seafood.","restaurant.ammoudi":"Relaxed seaside dining right by the water.","restaurant.pirounaki":"A traditional taverna choice for familiar Greek flavours.","restaurant.alexi":"One of our picks when the request is simple: real Greek food.","restaurant.perivoli":"A relaxed local recommendation for a traditional Greek meal.","restaurant.michalis":"Traditional food in Kampi and a good west-side stop.","restaurant.mouria":"A casual Greek meal in a seafront setting.","restaurant.redApple":"A relaxed local grill choice for straightforward Greek food and a casual evening.","restaurant.prasino":"A classic town-side recommendation when fish, seafood and Greek flavours are the priority.","restaurant.stathmos":"A warm, traditional choice in town for guests looking for a proper Greek meal rather than a polished tourist setting.","restaurant.mythos":"One of our picks for a traditional Greek souvlaki stop.","restaurant.thymari":"Grill, souvlaki and Greek comfort food for an easy local meal.","restaurant.pyra":"A modern meat-house choice for souvlaki and grilled meat in town.","restaurant.steki":"A local grill-house recommendation for souvlaki, grilled meat and a casual meal.","restaurant.movida":"Come here for the view as much as the evening itself. From Bochali, Movida overlooks Zakynthos Town and the island below — one of our strongest picks when the setting matters.","restaurant.base":"An all-day resto and cocktail bar in the heart of San Marco Square, suited to brunch, dinner or drinks in a more refined town setting.","restaurant.grace":"A contemporary town choice for a more polished evening, right in the centre of Zakynthos.","restaurant.vardiola":"Greek street food, souvlaki and lamb chops.","restaurant.wok":"Sushi and wok noodles for an easy takeaway option.","restaurant.demode":"Our sweet-stop pick for loukoumades, gelato, waffles and coffee.","restaurant.lete":"Sunset, cocktails and a west-coast view.","restaurant.keri":"A dramatic viewpoint over the Myzithres islets.","restaurant.grampsas":"A wine-focused local experience built around Zakynthian varieties.","restaurant.ampelostrates":"A rustic vineyard setting for a slower, more local side of Zakynthos.","restaurant.deli":"A useful local stop for fresh fruit and vegetables, cheeses, cold cuts, wines, spices, nuts, local products and deli essentials. There are two convenient locations, so guests can choose the one that best fits their route.",
    "location.town":"Zakynthos Town","location.krioneri":"Zakynthos Town · Krioneri","location.vanatoArea":"Vanato area","location.sanMarco":"Zakynthos Town · San Marco Square","location.limnionasArea":"Porto Limnionas area","location.townAlykanas":"ZAKYNTHOS TOWN & ALYKANAS","location.townArrow":"Zakynthos Town ↗",
    "experiences.eyebrow":"EXPERIENCES","experiences.title":"See a different side of the island.","experiences.boatLabel":"OUR BOAT PICK","experiences.boatTitle":"Explore Zakynthos from the sea","experiences.boatText":"Private boat experiences from Zakynthos Port aboard Kymothoe. Choose the south coast, Shipwreck and Blue Caves, a full-island day or ask about a special route.","experiences.boatButton":"Explore Nereids Voyaging ↗",
    "help.eyebrow":"USEFUL HELP DURING YOUR STAY","help.title":"Need help arranging something?","help.carTitle":"Car rental","help.carText":"Having a car is one of the easiest ways to explore Zakynthos. If you need a rental car, contact us and we can help you find a suitable option based on your dates and needs.","help.transportTitle":"Getting around","help.transportText":"If you need help getting to or from the airport, or arranging transportation during your stay, feel free to contact us. We may be able to help find a suitable option based on your route, time and group size.","help.contact":"Contact the person who shared this guide with you.",
    "last.eyebrow":"ONE LAST THING","last.title":"Ask us before you over-plan.","last.text":"Weather, sea conditions, driving time and access can completely change the best choice for a particular day. If you are unsure, contact the person who sent you this guide.","footer.text":"Places we love. Experiences worth having."
  },
  el: {
    "nav.beaches":"Παραλίες","nav.food":"Φαγητό","nav.experiences":"Εμπειρίες","nav.help":"Χρειάζεστε βοήθεια;",
    "hero.eyebrow":"ΕΝΑΣ ΕΠΙΛΕΓΜΕΝΟΣ ΟΔΗΓΟΣ ΓΙΑ ΤΗ ΖΑΚΥΝΘΟ","hero.title":"Ζάκυνθος,<br><em>με τον δικό μας τρόπο.</em>","hero.text":"Μέρη που αγαπάμε, εμπειρίες που αξίζουν και μερικές χρήσιμες συμβουλές για να αξιοποιήσετε στο έπακρο τη διαμονή σας.","hero.button":"Ξεκινήστε την εξερεύνηση",
    "intro.eyebrow":"Η ΤΟΠΙΚΗ ΜΑΣ ΕΠΙΛΟΓΗ","intro.title":"Όχι μια λίστα με τα πάντα.<br>Μόνο μέρη που πραγματικά προτείνουμε.","intro.text":"Επιλέξτε τι είδους ημέρα θέλετε, διαβάστε τις πρακτικές πληροφορίες και επικοινωνήστε με το άτομο που σας έστειλε αυτόν τον οδηγό, αν χρειάζεστε βοήθεια για την οργάνωση επιλεγμένων υπηρεσιών.",
    "beaches.eyebrow":"ΕΠΙΛΟΓΕΣ ΠΑΡΑΛΙΩΝ","beaches.title":"Τι είδους ημέρα στην παραλία αναζητάτε;","beaches.filter.all":"Όλες οι επιλογές","beaches.filter.favourite":"Οι αγαπημένες μας","beaches.filter.easy":"Εύκολη πρόσβαση","beaches.filter.scenic":"Καλύτερα νερά και τοπίο","beaches.filter.snorkel":"Κολύμπι και snorkeling","beaches.filter.wild":"Άγριες και αξίζουν τον κόπο",
    "common.goodToKnow":"Χρήσιμο να γνωρίζετε","common.map":"Προβολή στον χάρτη ↗",
    "beach.limnionas.label":"Η αγαπημένη μας","beach.limnionas.text":"Αν έπρεπε να επιλέξουμε μόνο ένα σημείο για κολύμπι στη Ζάκυνθο, θα ήταν αυτό. Βαθύ γαλάζιο νερό, εντυπωσιακά βράχια και εξαιρετικό κολύμπι.","beach.limnionas.note":"Η πρόσβαση περιλαμβάνει σκαλοπάτια και ανώμαλα, απότομα σημεία. Δεν συνιστάται για άτομα με περιορισμένη κινητικότητα ή για όσους δυσκολεύονται με απότομες καταβάσεις.",
    "beach.pelagaki.label":"Κρυφή αγαπημένη","beach.pelagaki.text":"Ένα μικρό, πανέμορφο σημείο με καθαρά τιρκουάζ νερά και πιο απομονωμένη ατμόσφαιρα.","beach.pelagaki.note":"Για να φτάσετε στην παραλία χρειάζεται να κατεβείτε αρκετά σκαλοπάτια. Λάβετέ το υπόψη για ηλικιωμένους ή για όποιον αναζητά εύκολη πρόσβαση.",
    "beach.xigia.label":"Φυσική ομορφιά","beach.xigia.text":"Μικροί όρμοι, εντυπωσιακό χρώμα νερού και ένα ιδιαίτερο φυσικό τοπίο.",
    "beach.roxa.label":"Βραχώδης όρμος","beach.roxa.text":"Ένα άγριο σημείο στη δυτική ακτή για βαθιά νερά και βραχώδες τοπίο.",
    "beach.banana.label":"Χαλαρή επιλογή","beach.banana.text":"Μια μεγάλη, οργανωμένη παραλία για μια εύκολη ημέρα με παροχές.",
    "beach.gerakas.label":"Προστατευόμενη ακτή","beach.gerakas.text":"Μια όμορφη αμμώδης παραλία στη χερσόνησο του Βασιλικού, μέσα στην προστατευόμενη περιοχή ωοτοκίας της θαλάσσιας χελώνας.",
    "beach.makris.label":"Βόρεια ακτή","beach.makris.text":"Τα καθαρά νερά και ο βραχώδης βυθός την κάνουν εξαιρετική επιλογή για κολύμπι και snorkeling.",
    "beach.schoinari.label":"Απόδραση στον βορρά","beach.schoinari.text":"Για εντυπωσιακό βόρειο τοπίο, βαθύ γαλάζιο νερό και μια πιο άγρια πλευρά της Ζακύνθου κοντά στις Γαλάζιες Σπηλιές.","beach.schoinari.note":"Ταιριάζει περισσότερο σε έμπειρους κολυμβητές και σε επισκέπτες που αισθάνονται άνετα σε βραχώδη σημεία. Δεν είναι μια κλασική ημέρα σε αμμώδη παραλία.",
    "beach.climati.label":"Ήσυχη αγαπημένη","beach.climati.text":"Ένας μικρός βοτσαλωτός όρμος με εξαιρετικά καθαρά νερά και ήσυχη ατμόσφαιρα. Πολύ καλή επιλογή για κολύμπι και snorkeling, μακριά από τις μεγάλες οργανωμένες παραλίες.","beach.climati.note":"Δεν υπάρχουν οι συνηθισμένες παροχές παραλίας ή σειρές από ξαπλώστρες. Ελάτε προετοιμασμένοι για μια απλή, φυσική στάση.",
    "beach.plakaki.label":"Αξίζει την προσπάθεια","beach.plakaki.text":"Θεαματικοί βραχώδεις σχηματισμοί στη δυτική ακτή και έντονα γαλάζια νερά. Μία από τις επιλογές μας για όσους αναζητούν κάτι άγριο και διαφορετικό.","beach.plakaki.note":"Η κατάβαση είναι απότομη και βραχώδης και απαιτεί κατάλληλα παπούτσια και προσοχή. Δεν τη συνιστούμε για ηλικιωμένους, άτομα με περιορισμένη κινητικότητα ή όσους δεν αισθάνονται άνετα με δύσκολη πρόσβαση.",
    "beach.korakonisi.label":"Φυσικό θαύμα","beach.korakonisi.text":"Ένας εντυπωσιακός βραχώδης κόλπος και φυσικό σημείο για κολύμπι, για όσους θέλουν να δουν ένα από τα πιο δραματικά παράκτια τοπία του νησιού.","beach.korakonisi.note":"Είναι ένα περιπετειώδες σημείο για κολύμπι και όχι συμβατική παραλία. Η διαδρομή προς τα κάτω είναι βραχώδης και απότομη, η σκιά περιορισμένη και η πρόσβαση δεν είναι κατάλληλη για όλους.",
    "beach.kalamaki.label":"Εύκολη αμμώδης επιλογή","beach.kalamaki.text":"Μια μεγάλη, αμμώδης και χαλαρή παραλία για επισκέπτες που θέλουν μια εύκολη ημέρα χωρίς δύσκολη κατάβαση.","beach.kalamaki.note":"Το Καλαμάκι βρίσκεται στην προστατευόμενη περιοχή ωοτοκίας της θαλάσσιας χελώνας. Σεβαστείτε τις σημειωμένες φωλιές, τις τοπικές οδηγίες και τυχόν περιορισμούς πρόσβασης.",
    "food.eyebrow":"ΦΑΓΗΤΟ ΚΑΙ ΠΟΤΟ","food.title":"Επιλέξτε ανάλογα με τη διάθεσή σας, όχι με κατάταξη.","food.filter.all":"Όλα τα μέρη","food.filter.special":"Κάτι πιο ξεχωριστό","food.filter.greek":"Αυθεντικό ελληνικό φαγητό","food.filter.souvlaki":"Παραδοσιακό σουβλάκι","food.filter.quick":"Γρήγορα και εύκολα","food.filter.sunset":"Ποτό και ηλιοβασίλεμα","food.filter.wine":"Κρασί και τοπικές γεύσεις","food.filter.deli":"Ντελικατέσεν και τοπικά προϊόντα",
    "restaurant.carissimo":"Μια αγαπημένη οικογενειακή επιλογή για ελληνική και μεσογειακή κουζίνα, με παραδοσιακές συνταγές και φιλική, χαλαρή ατμόσφαιρα. Ιδιαίτερα χρήσιμη πρόταση και για επισκέπτες που αναζητούν επιλογές χωρίς γλουτένη.","restaurant.nima":"Μια προσεγμένη επιλογή με έμφαση στα ψάρια και τα θαλασσινά.","restaurant.bassia":"Μεσογειακή κουζίνα με ιδιαίτερη έμφαση στα ψάρια και τα θαλασσινά.","restaurant.ammoudi":"Χαλαρό φαγητό δίπλα στη θάλασσα, ακριβώς πάνω στο νερό.","restaurant.pirounaki":"Παραδοσιακή ταβέρνα για γνώριμες ελληνικές γεύσεις.","restaurant.alexi":"Μία από τις επιλογές μας όταν η επιθυμία είναι απλή: αυθεντικό ελληνικό φαγητό.","restaurant.perivoli":"Μια χαλαρή τοπική πρόταση για παραδοσιακό ελληνικό γεύμα.","restaurant.michalis":"Παραδοσιακό φαγητό στην Καμπή και καλή στάση στη δυτική πλευρά του νησιού.","restaurant.mouria":"Χαλαρό ελληνικό γεύμα σε παραθαλάσσιο περιβάλλον.","restaurant.redApple":"Μια χαλαρή τοπική ψησταριά για απλό ελληνικό φαγητό και ανεπίσημο βραδινό.","restaurant.prasino":"Κλασική επιλογή κοντά στην πόλη όταν προτεραιότητα είναι τα ψάρια, τα θαλασσινά και οι ελληνικές γεύσεις.","restaurant.stathmos":"Μια ζεστή, παραδοσιακή επιλογή στην πόλη για όσους αναζητούν σωστό ελληνικό φαγητό και όχι ένα επιτηδευμένο τουριστικό περιβάλλον.","restaurant.mythos":"Μία από τις επιλογές μας για παραδοσιακό ελληνικό σουβλάκι.","restaurant.thymari":"Ψητά, σουβλάκι και αγαπημένες ελληνικές γεύσεις για ένα εύκολο τοπικό γεύμα.","restaurant.pyra":"Μια σύγχρονη επιλογή για σουβλάκι και ψητά κρέατα στην πόλη.","restaurant.steki":"Τοπική ψησταριά για σουβλάκι, ψητά κρέατα και χαλαρό γεύμα.","restaurant.movida":"Ελάτε τόσο για τη θέα όσο και για τη βραδινή έξοδο. Από τη Μπόχαλη, το Movida βλέπει προς την πόλη της Ζακύνθου και το νησί — μία από τις καλύτερες επιλογές μας όταν το περιβάλλον έχει σημασία.","restaurant.base":"All-day εστιατόριο και cocktail bar στην καρδιά της πλατείας Αγίου Μάρκου, κατάλληλο για brunch, δείπνο ή ποτό σε πιο προσεγμένο περιβάλλον.","restaurant.grace":"Μια σύγχρονη επιλογή στην πόλη για ένα πιο προσεγμένο βράδυ, ακριβώς στο κέντρο της Ζακύνθου.","restaurant.vardiola":"Ελληνικό street food, σουβλάκι και παϊδάκια αρνίσια.","restaurant.wok":"Sushi και noodles wok για εύκολη επιλογή takeaway.","restaurant.demode":"Η γλυκιά μας στάση για λουκουμάδες, παγωτό, βάφλες και καφέ.","restaurant.lete":"Ηλιοβασίλεμα, cocktails και θέα στη δυτική ακτή.","restaurant.keri":"Ένα εντυπωσιακό σημείο θέας προς τις Μυζήθρες.","restaurant.grampsas":"Μια τοπική εμπειρία κρασιού με βάση τις ζακυνθινές ποικιλίες.","restaurant.ampelostrates":"Ρουστίκ αμπελουργικό περιβάλλον για μια πιο αργή και αυθεντική πλευρά της Ζακύνθου.","restaurant.deli":"Χρήσιμη τοπική στάση για φρέσκα φρούτα και λαχανικά, τυριά, αλλαντικά, κρασιά, μπαχαρικά, ξηρούς καρπούς, τοπικά προϊόντα και είδη ντελικατέσεν. Υπάρχουν δύο βολικά καταστήματα, ώστε οι επισκέπτες να επιλέξουν εκείνο που ταιριάζει καλύτερα στη διαδρομή τους.",
    "location.town":"Πόλη Ζακύνθου","location.krioneri":"Πόλη Ζακύνθου · Κρυονέρι","location.vanatoArea":"Περιοχή Βανάτου","location.sanMarco":"Πόλη Ζακύνθου · Πλατεία Αγίου Μάρκου","location.limnionasArea":"Περιοχή Πόρτο Λιμνιώνα","location.townAlykanas":"ΠΟΛΗ ΖΑΚΥΝΘΟΥ ΚΑΙ ΑΛΥΚΑΝΑΣ","location.townArrow":"Πόλη Ζακύνθου ↗",
    "experiences.eyebrow":"ΕΜΠΕΙΡΙΕΣ","experiences.title":"Δείτε μια διαφορετική πλευρά του νησιού.","experiences.boatLabel":"Η ΕΠΙΛΟΓΗ ΜΑΣ ΓΙΑ ΣΚΑΦΟΣ","experiences.boatTitle":"Εξερευνήστε τη Ζάκυνθο από τη θάλασσα","experiences.boatText":"Ιδιωτικές εμπειρίες με σκάφος από το λιμάνι της Ζακύνθου, με το Kymothoe. Επιλέξτε τη νότια ακτή, το Ναυάγιο και τις Γαλάζιες Σπηλιές, μια ολοήμερη περιήγηση στο νησί ή ρωτήστε για μια ειδική διαδρομή.","experiences.boatButton":"Δείτε το Nereids Voyaging ↗",
    "help.eyebrow":"ΧΡΗΣΙΜΗ ΒΟΗΘΕΙΑ ΚΑΤΑ ΤΗ ΔΙΑΜΟΝΗ ΣΑΣ","help.title":"Χρειάζεστε βοήθεια για να οργανώσετε κάτι;","help.carTitle":"Ενοικίαση αυτοκινήτου","help.carText":"Το αυτοκίνητο είναι ένας από τους ευκολότερους τρόπους για να εξερευνήσετε τη Ζάκυνθο. Αν χρειάζεστε ενοικιαζόμενο αυτοκίνητο, επικοινωνήστε μαζί μας και μπορούμε να σας βοηθήσουμε να βρείτε την κατάλληλη επιλογή για τις ημερομηνίες και τις ανάγκες σας.","help.transportTitle":"Μετακινήσεις","help.transportText":"Αν χρειάζεστε βοήθεια για τη μεταφορά από ή προς το αεροδρόμιο ή για μετακινήσεις κατά τη διάρκεια της διαμονής σας, επικοινωνήστε μαζί μας. Μπορούμε να βοηθήσουμε να βρεθεί κατάλληλη επιλογή ανάλογα με τη διαδρομή, την ώρα και το μέγεθος της ομάδας σας.","help.contact":"Επικοινωνήστε με το άτομο που σας έστειλε αυτόν τον οδηγό.",
    "last.eyebrow":"ΜΙΑ ΤΕΛΕΥΤΑΙΑ ΣΥΜΒΟΥΛΗ","last.title":"Ρωτήστε μας πριν οργανώσετε τα πάντα.","last.text":"Ο καιρός, οι συνθήκες στη θάλασσα, ο χρόνος οδήγησης και η πρόσβαση μπορούν να αλλάξουν εντελώς την καλύτερη επιλογή για μια συγκεκριμένη ημέρα. Αν δεν είστε σίγουροι, επικοινωνήστε με το άτομο που σας έστειλε αυτόν τον οδηγό.","footer.text":"Μέρη που αγαπάμε. Εμπειρίες που αξίζουν."
  },
  it: {
    "nav.beaches":"Spiagge","nav.food":"Cibo","nav.experiences":"Esperienze","nav.help":"Serve aiuto?",
    "hero.eyebrow":"UNA GUIDA SELEZIONATA DI ZANTE","hero.title":"Zante,<br><em>a modo nostro.</em>","hero.text":"Luoghi che amiamo, esperienze che meritano e alcuni consigli utili per vivere al meglio il vostro soggiorno.","hero.button":"Inizia a esplorare",
    "intro.eyebrow":"LA SELEZIONE LOCALE","intro.title":"Non un elenco di tutto.<br>Solo luoghi che consigliamo davvero.","intro.text":"Scegliete il tipo di giornata che desiderate, leggete le informazioni pratiche e contattate la persona che vi ha condiviso questa guida se avete bisogno di aiuto per organizzare alcuni servizi.",
    "beaches.eyebrow":"SELEZIONE SPIAGGE","beaches.title":"Che tipo di giornata al mare state cercando?","beaches.filter.all":"Tutte le proposte","beaches.filter.favourite":"Le nostre preferite","beaches.filter.easy":"Comode e rilassanti","beaches.filter.scenic":"Acqua e paesaggi migliori","beaches.filter.snorkel":"Nuoto e snorkeling","beaches.filter.wild":"Selvagge, ma ne vale la pena",
    "common.goodToKnow":"Da sapere","common.map":"Vedi sulla mappa ↗",
    "beach.limnionas.label":"La nostra preferita","beach.limnionas.text":"Se dovessimo scegliere un solo posto dove nuotare a Zante, sceglieremmo questo. Acqua blu profonda, rocce spettacolari e nuoto eccellente.","beach.limnionas.note":"L’accesso comprende gradini e tratti irregolari e ripidi. Non è consigliato a persone con mobilità ridotta o a chi non si sente a proprio agio con discese difficili.",
    "beach.pelagaki.label":"Preferita nascosta","beach.pelagaki.text":"Un piccolo e bellissimo angolo con acqua turchese limpida e un’atmosfera più appartata.","beach.pelagaki.note":"Per raggiungere la spiaggia bisogna scendere un numero considerevole di gradini. Tenetelo presente per persone anziane o per chi cerca un accesso facile.",
    "beach.xigia.label":"Bellezza naturale","beach.xigia.text":"Piccole baie, un colore dell’acqua sorprendente e un ambiente naturale caratteristico.",
    "beach.roxa.label":"Baia rocciosa","beach.roxa.text":"Un punto selvaggio della costa occidentale, ideale per acqua profonda e paesaggi rocciosi.",
    "beach.banana.label":"Comoda e rilassante","beach.banana.text":"Una lunga spiaggia attrezzata, perfetta per una giornata semplice con tutti i servizi.",
    "beach.gerakas.label":"Costa protetta","beach.gerakas.text":"Una splendida spiaggia sabbiosa nella penisola di Vasilikos, all’interno dell’area protetta di nidificazione delle tartarughe marine.",
    "beach.makris.label":"Costa settentrionale","beach.makris.text":"L’acqua limpida e il fondale roccioso la rendono un’ottima scelta per nuotare e fare snorkeling.",
    "beach.schoinari.label":"Fuga a nord","beach.schoinari.text":"Per paesaggi spettacolari del nord, acqua blu profonda e un lato più selvaggio di Zante vicino alle Grotte Blu.","beach.schoinari.note":"È più adatta a nuotatori sicuri e a chi si trova a proprio agio in punti rocciosi. Non è la classica giornata su una spiaggia sabbiosa.",
    "beach.climati.label":"Preferita tranquilla","beach.climati.text":"Una piccola baia di ciottoli con acqua eccezionalmente limpida e un’atmosfera tranquilla. Ottima per nuotare e fare snorkeling lontano dalle grandi spiagge attrezzate.","beach.climati.note":"Non ci sono i classici servizi da spiaggia né file di lettini. Arrivate preparati per una sosta semplice e naturale.",
    "beach.plakaki.label":"Ne vale la pena","beach.plakaki.text":"Formazioni rocciose spettacolari sulla costa occidentale e acqua di un blu intenso. Una delle nostre proposte per chi cerca qualcosa di selvaggio e meno convenzionale.","beach.plakaki.note":"La discesa è ripida e rocciosa e richiede scarpe adatte e attenzione. Non la consigliamo a persone anziane, con mobilità ridotta o a chi non si sente a proprio agio con accessi difficili.",
    "beach.korakonisi.label":"Meraviglia naturale","beach.korakonisi.text":"Una suggestiva insenatura rocciosa e un punto naturale per nuotare, ideale per chi vuole vedere uno dei paesaggi costieri più spettacolari dell’isola.","beach.korakonisi.note":"È un luogo avventuroso per nuotare, non una spiaggia tradizionale. Il percorso è roccioso e ripido, l’ombra è limitata e l’accesso non è adatto a tutti.",
    "beach.kalamaki.label":"Scelta sabbiosa e comoda","beach.kalamaki.text":"Una spiaggia lunga, sabbiosa e rilassante per chi cerca una giornata facile senza una discesa impegnativa.","beach.kalamaki.note":"Kalamaki fa parte dell’area protetta di nidificazione delle tartarughe marine. Rispettate i nidi segnalati, le indicazioni locali e gli eventuali limiti di accesso.",
    "food.eyebrow":"CIBO E BEVANDE","food.title":"Scegliete in base all’atmosfera, non alla classifica.","food.filter.all":"Tutti i locali","food.filter.special":"Qualcosa di più speciale","food.filter.greek":"Autentica cucina greca","food.filter.souvlaki":"Souvlaki tradizionale","food.filter.quick":"Veloce e semplice","food.filter.sunset":"Drink e tramonto","food.filter.wine":"Vino e sapori locali","food.filter.deli":"Gastronomia e prodotti locali",
    "restaurant.carissimo":"Un ristorante familiare molto apprezzato per cucina greca e mediterranea, ricette locali e un’atmosfera amichevole e rilassata. È anche una proposta particolarmente utile per chi cerca opzioni senza glutine.","restaurant.nima":"Una scelta curata, incentrata su pesce e frutti di mare.","restaurant.bassia":"Cucina mediterranea con una forte attenzione a pesce e frutti di mare.","restaurant.ammoudi":"Cucina rilassata sul mare, proprio accanto all’acqua.","restaurant.pirounaki":"Una taverna tradizionale per i sapori greci più familiari.","restaurant.alexi":"Una delle nostre scelte quando la richiesta è semplice: vera cucina greca.","restaurant.perivoli":"Una proposta locale e rilassata per un pasto greco tradizionale.","restaurant.michalis":"Cucina tradizionale a Kampi e una buona sosta sul lato occidentale dell’isola.","restaurant.mouria":"Un pasto greco informale in un ambiente sul mare.","restaurant.redApple":"Una griglia locale e rilassata per cucina greca semplice e una serata informale.","restaurant.prasino":"Una scelta classica vicino alla città quando la priorità sono pesce, frutti di mare e sapori greci.","restaurant.stathmos":"Un locale caldo e tradizionale in città, per chi cerca un vero pasto greco invece di un ambiente turistico raffinato.","restaurant.mythos":"Una delle nostre proposte per un souvlaki greco tradizionale.","restaurant.thymari":"Griglia, souvlaki e sapori greci confortanti per un pasto locale semplice.","restaurant.pyra":"Una moderna meat house per souvlaki e carne alla griglia in città.","restaurant.steki":"Una griglia locale per souvlaki, carne alla brace e un pasto informale.","restaurant.movida":"Venite tanto per la vista quanto per la serata. Da Bochali, Movida domina la città di Zante e l’isola sottostante: una delle nostre proposte migliori quando l’ambiente conta.","restaurant.base":"Ristorante all-day e cocktail bar nel cuore di Piazza San Marco, adatto per brunch, cena o drink in un ambiente più raffinato.","restaurant.grace":"Una proposta contemporanea in città per una serata più elegante, proprio nel centro di Zante.","restaurant.vardiola":"Street food greco, souvlaki e costolette d’agnello.","restaurant.wok":"Sushi e noodles al wok per un takeaway semplice.","restaurant.demode":"La nostra tappa dolce per loukoumades, gelato, waffle e caffè.","restaurant.lete":"Tramonto, cocktail e vista sulla costa occidentale.","restaurant.keri":"Un punto panoramico spettacolare sugli isolotti di Myzithres.","restaurant.grampsas":"Un’esperienza enologica locale costruita intorno alle varietà di Zante.","restaurant.ampelostrates":"Un ambiente rustico tra i vigneti per scoprire il lato più lento e locale di Zante.","restaurant.deli":"Una comoda tappa locale per frutta e verdura fresca, formaggi, salumi, vini, spezie, frutta secca, prodotti locali e specialità gastronomiche. Ci sono due sedi comode, così gli ospiti possono scegliere quella più adatta al proprio itinerario.",
    "location.town":"Città di Zante","location.krioneri":"Città di Zante · Krioneri","location.vanatoArea":"Zona di Vanato","location.sanMarco":"Città di Zante · Piazza San Marco","location.limnionasArea":"Zona di Porto Limnionas","location.townAlykanas":"CITTÀ DI ZANTE E ALYKANAS","location.townArrow":"Città di Zante ↗",
    "experiences.eyebrow":"ESPERIENZE","experiences.title":"Scoprite un lato diverso dell’isola.","experiences.boatLabel":"LA NOSTRA SCELTA IN BARCA","experiences.boatTitle":"Esplorate Zante dal mare","experiences.boatText":"Esperienze private in barca dal porto di Zante a bordo di Kymothoe. Scegliete la costa meridionale, il Relitto e le Grotte Blu, una giornata intorno all’intera isola oppure chiedete un itinerario speciale.","experiences.boatButton":"Scopri Nereids Voyaging ↗",
    "help.eyebrow":"AIUTO UTILE DURANTE IL SOGGIORNO","help.title":"Avete bisogno di aiuto per organizzare qualcosa?","help.carTitle":"Noleggio auto","help.carText":"Avere un’auto è uno dei modi più semplici per esplorare Zante. Se avete bisogno di un’auto a noleggio, contattateci e possiamo aiutarvi a trovare una soluzione adatta alle vostre date e necessità.","help.transportTitle":"Come spostarsi","help.transportText":"Se avete bisogno di aiuto per raggiungere o lasciare l’aeroporto, oppure per organizzare spostamenti durante il soggiorno, contattateci. Possiamo aiutarvi a trovare una soluzione adatta in base al percorso, all’orario e al numero di persone.","help.contact":"Contattate la persona che vi ha condiviso questa guida.",
    "last.eyebrow":"UN’ULTIMA COSA","last.title":"Chiedeteci prima di pianificare troppo.","last.text":"Il meteo, le condizioni del mare, i tempi di guida e l’accesso possono cambiare completamente la scelta migliore per una determinata giornata. In caso di dubbi, contattate la persona che vi ha inviato questa guida.","footer.text":"Luoghi che amiamo. Esperienze che meritano."
  }
};

function applyLanguage(language) {
  const lang = translations[language] ? language : "en";
  const dictionary = translations[lang];

  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach(element => {
    const key = element.dataset.i18n;
    if (dictionary[key] !== undefined) element.textContent = dictionary[key];
  });
  document.querySelectorAll("[data-i18n-html]").forEach(element => {
    const key = element.dataset.i18nHtml;
    if (dictionary[key] !== undefined) element.innerHTML = dictionary[key];
  });

  const titles = {
    en: "The Zante Edit — Zakynthos Guide",
    el: "The Zante Edit — Οδηγός Ζακύνθου",
    it: "The Zante Edit — Guida di Zante"
  };
  document.title = titles[lang];
  localStorage.setItem("zanteEditLanguage", lang);
}

document.querySelectorAll(".filters").forEach(group => {
  const items = group.nextElementSibling.querySelectorAll("[data-tags]");
  group.querySelectorAll("button").forEach(button => {
    button.addEventListener("click", () => {
      group.querySelectorAll("button").forEach(item => item.classList.remove("active"));
      button.classList.add("active");
      const filter = button.dataset.filter;
      items.forEach(item => item.classList.toggle("hidden", filter !== "all" && !item.dataset.tags.split(" ").includes(filter)));
    });
  });
});

const languageSelect = document.getElementById("languageSelect");
const savedLanguage = localStorage.getItem("zanteEditLanguage");
const browserLanguage = navigator.language?.toLowerCase().startsWith("el") ? "el" : navigator.language?.toLowerCase().startsWith("it") ? "it" : "en";
const initialLanguage = savedLanguage || browserLanguage;
languageSelect.value = initialLanguage;
applyLanguage(initialLanguage);
languageSelect.addEventListener("change", event => applyLanguage(event.target.value));
